### ISSUE TITLE
Post-installation test fails (with singularity) due to incorrect number of available CPUs

### ISSUE THREAD

**Issue by kubu4** [EpiDiverse/wgbs#6]
I ran the test command:

`NXF_VER=20.07.1 ./nextflow run epidiverse/wgbs -profile test,singularity`

Encountered the following error message:

```
Pipeline execution summary
---------------------------
Name         : drunk_mandelbrot
Profile      : test,singularity
Launch dir   : /gscratch/srlab/programs
Work dir     : /gscratch/srlab/programs/work
Status       : failed
Error report : Error executing process > 'WGBS:read_trimming (sampleB)'
[-        ] process > INDEX:erne_bs5_indexing         [  0%] 0 of 1
[-        ] process > INDEX:segemehl_indexing         [  0%] 0 of 1
[6b/404951] process > WGBS:read_trimming (sampleB)    [ 50%] 1 of 2, failed: 1
[-        ] process > WGBS:read_merging               -
[-        ] process > WGBS:fastqc                     -
[-        ] process > WGBS:erne_bs5                   -
[-        ] process > WGBS:segemehl                   -
[-        ] process > WGBS:erne_bs5_processing        -
[-        ] process > WGBS:segemehl_processing        -
[-        ] process > WGBS:bam_merging                -
[-        ] process > WGBS:bam_subsetting             -
[-        ] process > WGBS:bam_filtering              -
[-        ] process > WGBS:bam_statistics             -
[-        ] process > CALL:bam_processing             -
[-        ] process > CALL:Picard_MarkDuplicates      -
[-        ] process > CALL:MethylDackel               -
[-        ] process > CALL:conversion_rate_estimation -
Oops... Pipeline execution stopped with the following message: null
Error executing process > 'WGBS:read_trimming (sampleB)'

Caused by:
  Process requirement exceed available CPUs -- req: 2; avail: 1

Command executed:

  mkdir fastq fastq/logs
  cutadapt -j 2 -a AGATCGGAAGAGC -A AGATCGGAAGAGC \
  -q 20 -m 36 -O 3 \
  -o fastq/input.sampleB_1.fastq.gz \
  -p fastq/input.sampleB_2.fastq.gz sampleB_1.fastq.gz sampleB_2.fastq.gz \
  > fastq/logs/cutadapt.sampleB.input.log 2>&1

Command exit status:
  -

Command output:
  (empty)

Work dir:
  /gscratch/srlab/programs/work/6b/40495111e640782bccc1d9e003c6ec

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`
```

When I look in the work dir specified above, there is no file `.command.sh` present:

```shell
$ cat /gscratch/srlab/programs/work/6b/40495111e640782bccc1d9e003c6ec/.command.sh

cat: /gscratch/srlab/programs/work/6b/40495111e640782bccc1d9e003c6ec/.command.sh: No such file or directory
```

Any suggestions on how to get this to execute successfully?

**Comment by bio15anu** [comment]
Hi, thanks for opening this issue. The test scenario is running on a basic assumption that there will be a limited number of computational resources available as defined in [base.config](https://github.com/EpiDiverse/wgbs/blob/6ae0222545ada30e64eb5bd9f3f4c053958b3d21/config/base.config) - but it is necessary to create your own configuration for optimising the pipelines on your own machine.

There are some basic instructions here: https://epidiverse.gitbook.io/project/-MfxkdBDZggX_vc_sG5l/epidiverse-pipelines/installation#3-pipeline-configuration but more simply put, the easiest thing would be to copy your own version of [base.config](https://github.com/EpiDiverse/wgbs/blob/6ae0222545ada30e64eb5bd9f3f4c053958b3d21/config/base.config) and modify the resource allocations accordingly to reflect your own system.

Then supply it as e.g. `-c /path/to/new/base.config`

**Comment by kubu4** [comment]
Gotcha. Thanks.

I'm not particularly well-versed in configuring Nextflow (and you can ignore this, since we're now deviating from pipeline-specific concerns), but is there a way to set the config file to _not_ require a specific number of CPUs? I.e. Set the config to use all available CPUs? It'd be great to not have a hard-coded CPU requirement.

**Comment by bio15anu** [comment]
We're touching here on a topic which quickly becomes very complex. Generally, it is expected that users have to get their hands dirty a bit with writing configuration files when working with nextflow pipelines (not just ours). As far as my experience with nextflow goes, it is not really possible for us to write a one-size-fits-all config which will work for absolutely everybody without issue. The best thing we can do is try to generalise an optimised config which hopefully works for _most_ people.

In our case we decided to optimise the config for a modern laptop configuration (8 threads, 16-32 Gb RAM), which is transferable in most cases also for running on HPC or the cloud. For the majority of people this should work efficiently out of the box, but we still expect some to have problems - and we are of course very happy to assist in modifying the config appropriately on a case-by-case basis to get it tailored for each user!

If we were to set all CPUs to 1, we will have people posting issues that the pipelines are very slow and they need help modifying the config to optimise them. If we set all CPUs to the maximum available, we will have people working on HPC posting issues that the pipelines hog all available resources and don't play well with queuing systems. So, I'm open to suggestions on how to improve this really but I don't know a good solution which will work for everybody.

I know that NF-core for example make use of a "maxThreads" and "maxMemory" function, where the user is expected to specify for example `--maxThreads 8` and then the pipeline automatically configures resource allocation appropriately. We could think more about something like that. Still in that case though, we would have to set a default and the user would be expected to optimise it themselves.

**Comment by kubu4** [comment]
Thanks for the suggestions/help!

In retrospect, after playing around with the pipelines on multiple computers and HPC nodes, this is likely an edge case scenario. I only encountered this using one of the "build nodes" on our HPC. These are nodes that have internet access, but are also granted "unlimited" CPU cycles (albeit, using only a single CPU thread) to allow for building programs from source, extracting tarballs, etc. Basically, allows the user to deal with stuff that isn't permitted on the login node, but wouldn't require significant resources that a "compute node" offers, as well as having a shorter queue due to the fact that a "build node" doesn't offer much computing power so people only use them for very short tasks.
